SELECT
    INVOICENO,
    STOCKCODE,
    TRIM(DESCRIPTION) AS DESCRIPTION,
    QUANTITY,
    UNITPRICE,
    QUANTITY * UNITPRICE AS total_amount,
    CUSTOMERID,
    COUNTRY,
    INVOICEDATE::DATE AS order_date
FROM {{ source('ecommerce', 'orders_raw') }}
WHERE
    CUSTOMERID IS NOT NULL
    AND QUANTITY > 0
    AND UNITPRICE > 0
    AND INVOICENO NOT LIKE 'C%'